name: Trigger Jenikins Build
on:
    #pull_request:
        #types: [opened, synchronize, reopened]
    push:
        branches: [develop, stage, master, test]
        paths:
        - 'bills-consumer/**'
        - 'bills-service/**'
        - 'bills/**'
        - 'kbus-integration/**'
    
    workflow_dispatch:

jobs:
# JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: get changed files
      id: getfile
      run: |
        echo "FILES= $( git diff --name-only ${{ github.event.before }} ${{ github.sha }} )" >> $GITHUB_ENV
        
    - name: get changed folder
      id: getfolder
      run: |
        if echo "${{ env.FILES }}" | awk '/bills-consumer\//{found=1} END{exit !found}'; then
            echo "SERVICE_NAME=bills-consumer" >> $GITHUB_ENV
        elif echo "${{ env.FILES }}" | awk '/bills-service\//{found=1} END{exit !found}'; then
            echo "SERVICE_NAME=bills-service" >> $GITHUB_ENV
        elif echo "${{ env.FILES }}" | awk '/bills\//{found=1} END{exit !found}'; then
            echo "SERVICE_NAME=bills" >> $GITHUB_ENV
        elif echo "${{ env.FILES }}" | awk '/kbus-integration\//{found=1} END{exit !found}'; then
            echo "SERVICE_NAME=kbus-integration" >> $GITHUB_ENV
        else
            echo "changes ${{ env.FILES }}"
            echo "servicenamepresent=YES" >> $GITHUB_OUTPUT
            exit 0
        fi

    - name: Determine if master branch
      if: github.ref_name == 'master'
      run: |
          echo "JENKINS_URL=${{ vars.CICD_PP_URL }}" >> $GITHUB_ENV
          echo "JENKINS_TOKEN=${{ secrets.CICD_PP_JENKINS_TOKEN }}" >> $GITHUB_ENV 
          
    - name: Determine if Dev or Stage branch
      if: github.ref_name == 'stage'|| 'develop' || 'test'
      run: |
          echo "JENKINS_URL=${{ vars.CICD_SANDBOX_URL }}" >> $GITHUB_ENV
          echo "JENKINS_TOKEN=${{ secrets.CICD_SANDBOX_JENKINS_TOKEN }}" >> $GITHUB_ENV 
                
    - name: Triggering Jenkins Build
      id: jenkins-job
      uses: toptal/jenkins-job-trigger-action@master
      with:
        jenkins_url: ${{ env.JENKINS_URL }}
        jenkins_user: ${{ secrets.CICD_USERNAME }}
        jenkins_token: ${{ env.JENKINS_TOKEN }}
        job_name: "builds/job/core/job/billing/job/${{ env.SERVICE_NAME }}/"
        job_params: |
          {
            "BRANCH": "${{ github.ref_name }}"
          }
        async: "true"
        
    - name: Slack Notifier
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: 'C05045MCZ7Z'
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "User: ${{ github.actor }} has raised a CR to ${{ github.event.repository.name }} => ${{ github.ref_name }}",
            "attachments": [
              {
                "pretext": "\nGitHub Action: ${{ github.workflow }}-${{ github.head_ref || github.run_id }} \nCR: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Jenkins job details",
                    "short": false,
                    "value": "\n${{ env.JENKINS_URL }}/job/builds/job/core/job/billing/job/${{env.SERVICE_NAME}}/"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.CICD_NOTIFIER_SLACK_BOT_TOKEN }}
                  