name: Trigger Jenkins Build
on:
  #pull_request:
      #types: [opened, synchronize, reopened]
  push:
      branches: [develop, stage, master, test]
jobs:
  job_name:
    name: Jenkins Build
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
    steps:
      - name: Determine if master branch
        if: contains(env.BRANCH, 'master')
        run: |
            echo "JENKINS_URL=${{ vars.CICD_PP_URL }}" >> $GITHUB_ENV
            echo "JENKINS_TOKEN=${{ secrets.CICD_PP_JENKINS_TOKEN }}" >> $GITHUB_ENV 
            
      - name: Determine if Dev or Stage branch
        if: contains(env.BRANCH, 'stage') || contains(env.BRANCH, 'develop')
        run: |
            echo "JENKINS_URL=${{ vars.CICD_SANDBOX_URL }}" >> $GITHUB_ENV
            echo "JENKINS_TOKEN=${{ secrets.CICD_SANDBOX_JENKINS_TOKEN }}" >> $GITHUB_ENV 
                 
      - name: Triggering Jenkins Build
        id: build_trigger
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: ${{ env.JENKINS_URL }}
          jenkins_user: ${{ secrets.CICD_USERNAME }}
          jenkins_token: ${{ env.JENKINS_TOKEN }}
          job_name: "/builds/job/core/job/${{ github.event.repository.name }}/"
          job_params: |
            {
              "BRANCH": "${{ env.BRANCH }}"
            }
          async: "true"
        
        
      - name: Slack Notifier
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C05045MCZ7Z'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "User: ${{ github.actor }} has raised a CR to repo: ${{ github.event.repository.name }} => Branch: ${{ github.ref_name }}",
              "attachments": [
                {
                  "pretext": "\nGitHub Action: ${{ github.event.workflow_run.jobs_url }} \nCR: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Jenkins job details",
                      "short": false,
                      "value": "\n${{ env.JENKINS_URL }}/job/builds/job/core/job/billing/job/${{env.SERVICE_NAME}}/"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.CICD_NOTIFIER_SLACK_BOT_TOKEN }}
        
     
