name: Trigger Jenikins Build
on:
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  job_name:
    name: Trigger Jenikins Build
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
    steps:
      - name: Determine if master branch
        if: contains(env.BRANCH, 'master')
        run: |
            echo "JENKINS_URL=${{ vars.CICD_PP_URL }}" >> $GITHUB_ENV
            echo "JENKINS_TOKEN=${{ vars.CICD_PP }}" >> $GITHUB_ENV 
            
      - name: Determine if Dev or Stage branch
        if: contains(env.BRANCH, 'stage') || contains(env.BRANCH, 'develop')
        run: |
            echo "JENKINS_URL=${{ vars.CICD_SANDBOX_URL }}" >> $GITHUB_ENV
            echo "JENKINS_TOKEN=${{ vars.CICD_SANDBOX }}" >> $GITHUB_ENV 
                 
      - name: Triggering Jenkins Build
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: ${{ env.JENKINS_URL }}
          jenkins_user: ${{ secrets.CICD_USERNAME }}
          jenkins_token: ${{ env.JENKINS_TOKEN }}
          # proxy: ${{ secrets.JENKINS_PROXY }}
          job_name: "builds/job/core/job/${{env.SERVICE_NAME}}/"
          job_params: |
            {
              "BRANCH": ${{ env.BRANCH }}
            }
              
        
       
